version: 2.1

jobs:
  conda_coverage:
    docker:
    - image: cimg/base:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_coverage.sh
  conda_release:
    docker:
    - image: cimg/base:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_release.sh
  conda_docs:
    docker:
    - image: cimg/base:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_docs.sh
  focal_clang9_debuggmp_unstable:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_clang9_debuggmp_unstable.sh
  focal_clang9_msan_00:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_clang9_msan.sh
        environment:
          TEST_NSPLIT: 2
          SPLIT_TEST_NUM: 0
  focal_clang9_msan_01:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_clang9_msan.sh
        environment:
          TEST_NSPLIT: 2
          SPLIT_TEST_NUM: 1
  conda_arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_arm64.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    # - focal_clang9_msan_00
    # - focal_clang9_msan_01
    - conda_coverage
    - conda_release
    # - focal_clang9_debuggmp_unstable
    - conda_docs
    - conda_arm64
