name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  osx_11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_osx.sh
  conda_asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_asan.sh
  conda_ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_ubsan.sh
  conda_tsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_tsan.sh
  conda_debuggmp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_debuggmp.sh
  binder_cache:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
